### ISSUE TITLE
Error message when using sky_subtract

### ISSUE THREAD

**Issue by astrocaroline** [OttoStruve/muler#40]
Running the current version of the code, I get an error message when I run sky_subtract that looks related to astropy. I can solve this by adding "import astropy" and rerunning.

**Comment by kfkaplan** [comment]
Can you copy and paste the error message here?

**Comment by gully** [comment]
During an in-person workshop, Caroline, others and I decided that the root cause of this issue is an astropy/specutils dependency somewhere.  We decided that the best way forward would be to set up a GitHub Actions Continuous Integration testing cycle, with a build matrix for python, astropy, and possibly specutils.  

Setting this up will take a little work, but will help maintain the code in the long-run.

**Comment by gully** [comment]
Yay! This error message should not occur any more with the new-and-improved installation guidance in the `setup.py` and new streamlined pip installation.  Please update your `muler` install if you are seeing this message, and reopen this Issue if the problem persists. :smiley:
