### ISSUE TITLE
trim_edges not working for IGRINS example data

### ISSUE THREAD

**Issue by gmace** [OttoStruve/muler#73]
<img width="1085" alt="Screen Shot 2021-12-03 at 12 39 56 PM" src="https://user-images.githubusercontent.com/4945411/144655735-0ea682b8-099c-4936-8a12-f426d407cccf.png">

**Comment by gully** [comment]
:pray: Thank you Greg for filing this Issue! I am see the problem!  It occurs here:

https://github.com/OttoStruve/muler/blob/ed7d092fbfaf87b22c622cd7264859fb1219ac4a/src/muler/echelle.py#L542-L546

The `x_values` are the native IGRINS pixels, and `muler` aspires to maintain this ancillary pixel label through all operations.  Somehow that aspiration has fallen short here, which has caused a bug.  The offending spectrum is the final order, number 27.  If you isolate that spectrum: `spec = spec_list[27]`, you can see that the pixels are not getting properly accounted for in the masking process:



![Screenshot from 2021-12-03 17-03-04](https://user-images.githubusercontent.com/860227/144684022-40b18284-9142-4fcd-910e-4ce00810bc2e.png)


I will take a look at why the masking is not correctly applied to the x_values.

An alternative solution is that specutils should keep track of the pixel labels.  They might have a mechanism for doing that, and if they do I'd prefer to use their method over ours!  

Thanks again for raising the issue! :)

**Comment by gully** [comment]
Hi @gmace I found the problem, it was due to line 542 above--- a dictionary key is not considered an attribute, so the conditional on line 542 was never met.  This bug appeared in two places, so I have fixed both locations.  You can now conduct `trim_edges` and `remove_nans` in any order.  :pray: Thank you again for filing the Issue, which brought the problem to our attention.

Moving forward we have also added this scenario as a test case so that everytime the code changes, we will make sure routine operations like these successfully commute.  

Please update your `muler` installation with `git pull origin main`, restart your Jupyter notebook, and verify that the solution resolved your Issue.  Thanks again!
